### PR TITLE
Only publish on release branch

### PR DESCRIPTION
**Pull request by carlcsaposs-canonical**

### CODE REVIEW

**Comment by jardon** [comment]
Can we do `*.*/*` instead?  This would grab all branches with the `MAJOR.MINOR/RISK` naming convention.

**Comment by carlcsaposs-canonical** [comment]
> Can we do `*.*/*` instead? This would grab all branches with the `MAJOR.MINOR/RISK` naming convention.

:+1: 

I think `[0-9]+.[0-9]+/*` might also work. @jardon Which do you prefer? (feel free to commit directly to this branch)

**Comment by jardon** [comment]
if `[0-9]+.[0-9]+/*` works then that is more than okay with me

**Comment by carlcsaposs-canonical** [comment]
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet

**Review by jardon — APPROVED** [review]
Thanks for the PR!

**Review by paulomach — APPROVED** [review]

**Pull request merged**
