### PR TITLE
Added a badge for the publish workflow

### PR DESCRIPTION
**Pull request by a-velasco**
## Issue
This repo's status is not displayed in the [Charm Engineering Releases](https://releases.juju.is/?team=Data) overview.

## Solution
Added a badge for the "publish" workflow.

@ reviewers, does this make sense?

### CODE REVIEW

**Comment by paulomach** [comment]
> @ reviewers, does this make sense?

@a-velasco what's the meaning of the publish badge? If it's the state of publish of the last merge on the branch, then imo it makes sense

**Comment by a-velasco** [comment]
> @a-velasco what's the meaning of the publish badge? If it's the state of publish of the last merge on the branch, then imo it makes sense

@paulomach I'm not 100% sure myself. The badge is directly related to the [publish.yaml](https://github.com/canonical/mysql-router-snap/blob/8.0/edge/.github/workflows/publish.yaml) file, which I chose because it looks like the workflow that publishes this to the snap store.

**Review by taurus-forever — APPROVED** [review]

**Review by taurus-forever — COMMENTED** [review]
The repository is no longer is use and should  be archived.

**Comment by taurus-forever** [comment]
Closing to archive the repo...

**Pull request closed without merging**
